name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 black pytest
    
    - name: Lint with flake8
      run: |
        flake8 streamlit_app.py --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 streamlit_app.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Format check with black
      run: black --check streamlit_app.py
    
    - name: Run tests
      run: pytest tests/ -v || echo "No tests found"
    
    - name: Validate requirements
      run: pip check

  deploy-check:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    
    - name: Deployment ready
      run: |
        echo "✓ All checks passed"
        echo "Deploy at: https://share.streamlit.io/"
        echo "Repository: ${{ github.repository }}"
        echo "Commit: ${{ github.sha }}"
